### ISSUE TITLE
Installation with OroCRM 1.6.1 fails

### ISSUE THREAD

**Issue by patbaumgartner** [orocrm/OroCRMMailChimpBundle#2]
Installation on the command line is failing, because DB table already exists.

#require oro bundle
root@ac1c481d9795:/var/www/vhosts/orocrm# composer require oro/crm-mail-chimp
Using version ~1.0@dev for oro/crm-mail-chimp
./composer.json has been updated

#clearing cache
root@ac1c481d9795:/var/www/vhosts/orocrm# rm -rf app/cache/*

#manual installation
root@ac1c481d9795:/var/www/vhosts/orocrm# app/console oro:platform:update --env prod --force
Process migrations...
  > OroCRM\Bundle\MailChimpBundle\Migrations\Schema\OroCRMMailChimpBundleInstaller
    ERROR: The table with name 'orocrm.orocrm_mc_mmbr_activity' already exists.
  > Oro\Bundle\MigrationBundle\Migration\UpdateBundleVersionMigration
  > Oro\Bundle\EntityExtendBundle\Migration\RefreshExtendCacheMigration - skipped
  > Oro\Bundle\EntityConfigBundle\Migration\UpdateEntityConfigMigration - skipped
  > Oro\Bundle\EntityExtendBundle\Migration\UpdateExtendConfigMigration - skipped
  > Oro\Bundle\ActivityListBundle\Migration\ActivityListMigration - skipped
  > Oro\Bundle\EntityExtendBundle\Migration\UpdateExtendIndicesMigration - skipped

                                                                                                      
  [RuntimeException]                                                                                  
  Failed migrations: OroCRM\Bundle\MailChimpBundle\Migrations\Schema\OroCRMMailChimpBundleInstaller.

**Comment by rgrebenchuk** [comment]
Hi,
Сould you try on new DB ? This table could be created with doctrine:schema:update or from a previous installation.

**Comment by patbaumgartner** [comment]
a fresh DB and composer require oro/crm-mail-chimp:1.2.1 does the job. Thanks your support!
