### ISSUE TITLE
Bundle not installable

### ISSUE THREAD

**Issue by phishee** [orocrm/OroCRMMailChimpBundle#3]
I have cannot seem to solve the following issue with the installation of the MailChimp Bundle - I am on a 1.6.1 version of OroCRM.  Any ideas??

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for oro/crm-mail-chimp 1.2 -> satisfiable by oro/crm-mail-chimp[1.2.0].
    - Installation request for composer/composer == 1.0.0.0-alpha8 -> satisfiable by composer/composer[1.0.0-alpha8].
    - remove oro/platform 1.x-dev|keep oro/platform dev-master
    - Conclusion: remove oro/platform dev-master
    - oro/platform 1.x-dev requires composer/composer 1.0.0-alpha9 -> satisfiable by composer/composer[1.0.0-alpha9].
    - oro/platform 1.x-dev requires composer/composer 1.0.0-alpha9 -> satisfiable by composer/composer[1.0.0-alpha9].
    - Conclusion: don't install composer/composer 1.0.0-alpha9
    - Installation request for oro/platform == 1.9999999.9999999.9999999-dev -> satisfiable by oro/platform[1.x-dev].

Installation failed, reverting ./composer.json to its original content.

**Comment by sergeyz** [comment]
Hi @phishee !

Issue with composer in platform was fixed
