### ISSUE TITLE
[Error #250] FREQUENCY must be provided - Please enter a value

### ISSUE THREAD

**Issue by tim-massey** [orocrm/OroCRMMailChimpBundle#4]
Can you help me diagnose why this is appearing in the logs?

The FREQUENCY is a required field on our list.

**Comment by sergeyz** [comment]
Hi, @tim-massey !

Please provide more information about this field and your expectations.
Our Member doesn't contains it

**Comment by mkudelya** [comment]
I am now closing this issue as it has been inactive for a while. Please, feel free to reopen it if you have any questions.
