### ISSUE TITLE
Doesn't work with OroCRM 1.10

### ISSUE THREAD

**Issue by startupz** [orocrm/OroCRMMailChimpBundle#5]
Requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove oro/platform 1.8.0
    - Installation request for oro/crm-mail-chimp dev-master -> satisfiable by oro/crm-mail-chimp[dev-master].
    - Conclusion: don't install oro/platform 1.8.0
    - Conclusion: don't install oro/platform 1.8.0
    - oro/crm-mail-chimp dev-master requires oro/crm 1.x-dev -> satisfiable by oro/crm[1.x-dev].
    - oro/crm 1.x-dev requires oro/platform 1.x-dev -> satisfiable by oro/platform[1.x-dev].
    - oro/crm 1.x-dev requires oro/platform 1.x-dev -> satisfiable by oro/platform[1.x-dev].
    - Can only install one of: oro/platform[1.x-dev, 1.8.0].
    - Can only install one of: oro/platform[1.x-dev, 1.8.0].
    - Installation request for oro/platform == 1.8.0.0 -> satisfiable by oro/platform[1.8.0].

Could you update the composer.json in order to use it with OroCRM EE 1.10?

**Comment by rgrebenchuk** [comment]
Hi,
For stable versions please use stable 1.4.* OroCRMMailChimpBundle version

**Comment by startupz** [comment]
It works!
